version: '3'
services:
  eurekaserver:
    image:   coopersoft/cloud-eurekasvr:latest
    #    deploy:
    #      resources:
    #        limits:
    ##          cpus: '0.05'
    #          memory: 360M
    #        reservations:
    ##          cpus: '0.01'
    #          memory: 128M
    ports:
      - "8761:8761"
    environment:
      TZ: Asia/Shanghai
  configserver:
    image: coopersoft/cloud-confsvr:latest
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY:       "IMSYMMETRIC"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
    depends_on:
      - eurekaserver
  zuulserver:
    image: coopersoft/cloud-zuulsvr:latest
    #    deploy:
    #      resources:
    #        limits:
    #          #          cpus: '0.05'
    #          memory: 360M
    #        reservations:
    #          #          cpus: '0.01'
    #          memory: 128M
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
      - configserver:configserver
    depends_on:
      - eurekaserver
      - configserver
  database:
    image: coopersoft/mariadb-min:v1
    #      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "3306:3306"
    volumes:
      - "/home/docker/data/db:/var/lib/mysql"
    environment:
      #      - MYSQL_ROOT_PASSWORD=p0stgr@s
      #      - MYSQL_DATABASE=archives
      MYSQL_DATABASE: archives
      MYSQL_ROOT_PASSWORD: p0stgr@s
      #      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
  #        - MYSQL_USER=testuser
  #        - MYSQL_PASSWORD=testpassword


  #        docker run --name mariadb_test -e MYSQL_ROOT_PASSWORD=my-secret=pw -d
  #        docker run -d --name mariadb_volume -P -v /data/Db/mariadb:/var/lib/mysql mariadb
  #          nosse4  stable4


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data/redis:/data"
    command: redis-server --requirepass p0stgr@s

  rmqnamesrv:
    image: rocketmqinc/rocketmq
    ports:
      - 9876:9876
    volumes:
      - /home/docker/data/rocketmq/logs:/home/rocketmq/logs
      - /home/docker/data/rocketmq/store:/home/recketmq/store
    command: sh mqnamesrv

  rmqborker:
    image: rocketmqinc/rocketmq
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - /home/docker/data/rocketmq/logs:/home/rocketmq/logs
      - /home/docker/data/rocketmq/store:/home/rocketmq/store
      - /home/docker/data/rocketmq/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    command: sh mqbroker -n rmqnamesrv:9876 -c ../conf/broker.conf
    links:
      - rmqnamesrv:rmqnamesrv
    depends_on:
      - rmqnamesrv


  # rocket 控制台 非必要
  rmqconsole:
    image: styletang/rocketmq-console-ng
    ports:
      - 8087:8080
    depends_on:
      - rmqnamesrv
    links:
      - rmqnamesrv:rmqnamesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rmqnamesrv:9876
      - Dcom.rocketmq.sendMessageWithVIPChannel=false


  authenticationservice:
    image: coopersoft/cloud-authentication-service:latest
      #deploy:
      #resources:
      #limits:
      #          cpus: '0.05'
      #memory: 360M
      #reservations:
      #          cpus: '0.01'
    #memory: 128M
    ports:
      - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      DATABASE_PORT:     3306
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY:       "IMSYMMETRIC"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
      - database:database
      - configserver:configserver
    depends_on:
      - eurekaserver
      - database
      - configserver

  # ==================  archive app ===================================================

  corpservices:
    image: coopersoft/construct-attach-corp-service:snapshot
    #    deploy:
    #      resources:
    #        limits:
    #          #          cpus: '0.05'
    #          memory: 360M
    #        reservations:
    #          #          cpus: '0.01'
    #          memory: 128M

    expose:
      - "19001"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "19001"
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      AUTHSERVER_PORT:   8091
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      AUTHSERVER_URI:   "http://authenticationservice/auth/user"
      ENCRYPT_KEY:       "IMSYMMETRIC"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
      - database:database
      - configserver:configserver
      - rmqnamesrv:rmqnamesrv
    depends_on:
      - eurekaserver
      - database
      - configserver
      - rmqnamesrv



  cacheservices:
    image: coopersoft/construct-project-cache-service:snapshot
    expose:
      - "19003"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "19003"
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      AUTHSERVER_PORT:   8091
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      AUTHSERVER_URI:   "http://authenticationservice/auth/user"
      ENCRYPT_KEY:       "IMSYMMETRIC"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
      - configserver:configserver
      - rmqnamesrv:rmqnamesrv
      - redis:redis
    depends_on:
      - eurekaserver
      - configserver
      - rmqnamesrv
      - redis