version: '3'
services:
  database:
    image: coopersoft/mariadb-min:v1
    ports:
      - "3306:3306"
    volumes:
      - "/home/data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: p0stgr@s
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: k@ycl0ck
      TZ: Asia/Shanghai

  mediaservice:
    image: coopersoft/archives-media-service:stable2
    ports:
      - "6699:6699"
    volumes:
      - "/home/data/weedfs:/data"


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data/redis:/data"
    command: redis-server --requirepass p0stgr@s

  rmqnamesrv:
    image: rocketmqinc/rocketmq
    ports:
      - 9876:9876
    volumes:
      - /home/data/rocketmq/logs:/home/rocketmq/logs
      - /home/data/rocketmq/store:/home/recketmq/store
    command: sh mqnamesrv

  rmqborker:
    image: rocketmqinc/rocketmq
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - /home/data/rocketmq/logs:/home/rocketmq/logs
      - /home/data/rocketmq/store:/home/rocketmq/store
      - /home/data/rocketmq/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    command: sh mqbroker -n rmqnamesrv:9876 -c ../conf/broker.conf
    links:
      - rmqnamesrv:rmqnamesrv
    depends_on:
      - rmqnamesrv


  # rocket 控制台 非必要
  rmqconsole:
    image: styletang/rocketmq-console-ng
    ports:
      - 8087:8080
    depends_on:
      - rmqnamesrv
    links:
      - rmqnamesrv:rmqnamesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info -Drocketmq.namesrv.addr=rmqnamesrv:9876
      - Dcom.rocketmq.sendMessageWithVIPChannel=false


  consul:
    image: consul:latest
    command: agent -server -bootstrap -ui -node=node1 -client=0.0.0.0
    ports:
      - 8500:8500
    volumes:
      - /home/consul:/consul/data


  keycloak:
    image: jboss/keycloak
    ports:
      - 8901:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mariadb
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: k@ycl0ck
      DB_PORT: 3306
    links:
      - database:database
    depends_on:
      - database


  gatewaysvr:
    image: coopersoft/cloud-gatewaysvr:snapshot
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    depends_on:
      - consul
    links:
      - consul:consul

  # ==================  archive app ===================================================

  corpservices:
    image: coopersoft/construct-attach-corp-service:snapshot
    expose:
      - "19001"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "19001"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - database:database
      - rmqnamesrv:rmqnamesrv
      - keycloak:keycloak
      - consul:consul
    depends_on:
      - database
      - rmqnamesrv
      - keycloak
      - consul

  projectservices:
    image: coopersoft/construct-project-service:snapshot
    expose:
      - "19002"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "19002"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - database:database
      - rmqnamesrv:rmqnamesrv
      - keycloak:keycloak
      - consul:consul
    depends_on:
      - database
      - rmqnamesrv
      - keycloak
      - consul

  cacheservices:
    image: coopersoft/construct-project-cache-service:snapshot
    expose:
      - "19003"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "19003"
      CONSULSERVER_PORT: 8500
      CONSULSERVER_HOST: "consul"
      TZ: Asia/Shanghai
    links:
      - rmqnamesrv:rmqnamesrv
      - redis:redis
      - keycloak:keycloak
      - consul:consul
    depends_on:
      - redis
      - rmqnamesrv
      - keycloak
      - consul