
#config/construct-attach-corp:dev/data
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    cc.coopersoft: DEBUG


spring:
  jpa:
    show-sql: "true"
